name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'oracle'

      - name: build rsa-plugin-cli
        run: mvn --batch-mode --update-snapshots -f rsa-plugin-cli package

      - name: build rsa-plugin-provider
        run: mvn --batch-mode --update-snapshots -f rsa-plugin-provider package


