name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build rsa-plugin-cli
        run: mvn --batch-mode --update-snapshots -f rsa-plugin-cli

      - name: build rsa-plugin-provider
        run: mvn --batch-mode --update-snapshots -f rsa-plugin-provider
